<?xml version="1.0" encoding="utf-8"?>
<Project>

  <ItemGroup>
    <ClInclude Include="..\Wrapper\PreCompile.h" />
    <ClInclude Include="..\Wrapper\resource.h" />

    <ClInclude Include="..\Wrapper\BaseballScoreTypes.h" />
    <ClInclude Include="..\Wrapper\DocumentFile.h" />
    <ClInclude Include="..\Wrapper\ScoreDocument.h" />
    <ClInclude Include="..\Wrapper\ScoreInterface.h" />
  </ItemGroup>

  <ItemGroup>
    <ClCompile Include="..\Wrapper\AssemblyInfo.cpp" />
    <ClCompile Include="..\Wrapper\DocumentFile.cpp" />
    <ClCompile Include="..\Wrapper\ScoreDocument.cpp" />
    <ClCompile Include="..\Wrapper\ScoreInterface.cpp" />
  </ItemGroup>

  <ItemGroup>
    <Text Include="..\Wrapper\ReadMe.txt" />
  </ItemGroup>
  <ItemGroup>
    <ResourceCompile Include="..\Wrapper\app.rc" />
  </ItemGroup>
  <ItemGroup>
    <Image Include="..\Wrapper\app.ico" />
  </ItemGroup>

</Project>
